### ISSUE TITLE
Custom Build Config for only Decoding VP8

### ISSUE THREAD

**Issue by waldobeest** [Yahweasel/libav.js#15]
Hi Yahweasel, 

Once again, super project, thanks!

I have a question on a custom build config to reduce the library size for only needing to decode vp8 in the browser. 

Some background on what I am trying to do, the videos I am decoding have no audio, so it needs no flac or ogg support. They are only a few resolutions needed, and I only need the decoding from vp8 webm done in the browser.

My build configs:
```
deps.txt
tmp-inst/@TARGET/lib/pkgconfig/vpx.pc
```
```
ffmpeg-config.txt
--enable-libvpx
--enable-decoder=libvpx_vp8
```
```
libs.txt
tmp-inst/@TARGET/lib/libvpx.a
```
```
link-flags.txt
-DLIBAVJS_WITH_SWSCALE=1
```

The builds are successful, and have reduced the size as needed, but in turn have some errors in processing in the browser. 
<img width="1341" alt="image (98)" src="https://user-images.githubusercontent.com/35687517/223649915-c9e60a52-7a11-4f67-9bf1-ed6e26ebd68e.png">

I also tried with:
```
ffmpeg-config.txt
--enable-protocol=data --enable-protocol=file
--enable-filter=aresample
--enable-libvpx
--enable-decoder=libvpx_vp8
--enable-encoder=libvpx_vp8
```
and getting:

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/35687517/223650091-0c9e9f62-b1ed-4d00-9d79-4f4cd00bb84f.png">

Any way that you can see we can achieve this, or is the best way to roll with the config for the `webm-flac-opus`?

**Comment by Yahweasel** [comment]
It looks like you're using avformat_open_input_js, i.e., you're not just decoding VP8, you're also demuxing WebM. If you want to be able to demux WebM, you need to include the WebM format. You should create the configuration like so:

```shell
$ cd configs
$ ./mkconfig.js webm-decode '["webm","vpx","vp8"]'
```

**Comment by Yahweasel** [comment]
Closing as presumably complete.
