### ISSUE TITLE
ff_init_encoder is broken in master

### ISSUE THREAD

**Issue by martenrichter** [Yahweasel/libav.js#28]
Hi, just a small thing, commit
https://github.com/Yahweasel/libav.js/commit/be78716e9101495e7a87dce35acdb373c4a3d509
breaks `ff_init_encoder`, since it uses `av_dict_set` and  `av_dict_free`, and the commit removes them in favor of
 `av_dict_set_js`. But I assume, you are aware of it and I have just bad luck getting a commit in the middle of an interface remodeling.

**Comment by Yahweasel** [comment]
Yeah, I only made that change a day or so ago, and as you suspected, I haven't yet pushed it through the other interfaces. But, I'll leave this open as you're entirely correct that at present that's broken.

**Comment by martenrichter** [comment]
Fine, then I use a commit before for experiments..... Yes leave it open, if someone tries, saves some time. For reference, 95a23d712519adaecb76f653e55df0ecd4355d6b should be save to use until the interface change is completed.
