### ISSUE TITLE
Resampling

### ISSUE THREAD

**Issue by BobbyShoe** [Yahweasel/libav.js#3]
The docs mention libswresample is included, but I do not see any resampling classes in bindings.c

In other projects I have used SwrContext to do resampling within FFmpeg.  Is there anything similar available in libav.js?

Thanks.

**Comment by Yahweasel** [comment]
I don't have bindings directly to libswresample, I just have resampling supported by way of the aresample filter. I'll admit the only reason for this is that I've never actually _used_ libswresample directly myself, only by way of the aresample filter :). I believe that anything one can do with libswresample one can also do indirectly via its avfilter. Nonetheless, I'll consider adding a direct interface.

**Comment by BobbyShoe** [comment]
Took me a while, but I got it working with the aresample filter.  Thanks for the suggestion.
