### ISSUE TITLE
Support for AIFF

### ISSUE THREAD

**Issue by maximedupre** [Yahweasel/libav.js#30]
I'm not sure if the lib supports AIFF or not, but I've tried all variants and it seems like I can't load such a file.

> Error: Could not open source file

Error occurs at this call: `avformat_open_input_js(filename, fmt ? fmt : null, null)`

My end goal is to be able to convert an AIFF file to a WAV file.

My code so far is

```javascript
const libav = await LibAV.LibAV({ noworker: true });

const arrayBuffer = new Uint8Array(
    await (await fetch('./sample.aiff')).arrayBuffer()
);

await libav.writeFile('sample.aiff', arrayBuffer);

const [fmt_ctx, [stream]] = await libav.ff_init_demuxer_file(
    'sample.aiff'
);
// ^ fails
```

Thanks 🙏

**Comment by Yahweasel** [comment]
None of the configurations as stand support AIFF, unfortunately, but it's fairly straightforward to add (assuming you have Emscripten and so can compile libav.js). To do that, you've got two direct options:

(1) Create your own configuration by copying one of the existing config/ directories, then add the relevant AIFF steps, or
(2) Add a new entry in mkconfigs.js that has the following additions: `"format-aiff", "codec-pcm_s16be", "codec-pcm_s32be", "codec-f32be"`, then just run mkconfigs.js to make your configuration.

You're not the first person to ask for AIFF, so maybe it's time to just have a variant that supports it (probably a "raw and lossless" variant). The variants that are here largely just reflect demand.

**Comment by Yahweasel** [comment]
Use `make build-<variant>`, e.g. `make build-aiff` if you named your variant `aiff`.

(By the way, although it's harmless, you don't need to use `emmake make` for libav.js. Its Makefile calls emconfigure and emmake for the subprojects automatically, since it's only built to build with Emscripten anyway.)

**Comment by zquintana** [comment]
@Yahweasel , do you plan to add the configuration preset? It seems like there are a number of steps beyond just adding the configuration to be able to use this with aiff.

**Comment by Yahweasel** [comment]
> [@Yahweasel](https://github.com/Yahweasel) , do you plan to add the configuration preset? It seems like there are a number of steps beyond just adding the configuration to be able to use this with aiff.

My configuration presets are already pushing size limits, and I'm not convinced that aiff is sufficiently important to justify having a prebuilt version of it. The world of file formats is an endless slippery slope, and a line has to be drawn somewhere.

The only step beyond adding the configuration is building with that configuration, but indeed, if you're unaccustomed to building Emscripten projects, that can seem fairly onerous.

**Comment by Yahweasel** [comment]
(Those steps can also be automated, of course)

**Comment by zquintana** [comment]
I notice in that example `mkconfig.sh` calls `./mkconfig.js`, but I don't see `mkconfig.js` in that repo. Is that something in this repo?
