### ISSUE TITLE
Get progress for `ffmpeg()`

### ISSUE THREAD

**Issue by reinhrst** [Yahweasel/libav.js#37]
I was wondering if there is some way to get progress information when using `ffmpeg()`

I'm doing a simple remuxing (`input.MTS -c:v copy -an -y output.mp4`), and it takes 1 or two minutes for a 4GB file. This is completely acceptable, but it would be good if there is some way to keep track of progress to show some sort of progress bar.

I _could_ manually do the remux (and have a progress bar) but I think ffmpeg does some special things that I would have to find out how to add.

I _could_ also keep track of how many bytes were written and (considering that in this case output is going to be something like 95% of input), make something useful, but that is very specific to this case.

I guess that getting access to the default `ffmpeg` stdout would already do the trick (since I could parse it and get the info I need), but there may also be some other way.

**Comment by marcello3d** [comment]
You can use the -progress option in ffmpeg and write to a writer device

**Comment by reinhrst** [comment]
Perfect, thanks! Makes sense that the answer was in ffmpeg's command line options :)
