### ISSUE TITLE
please replace STACK_SIZE with TOTAL_STACK in makefile to compile with latest emcc compilers 

### ISSUE THREAD

**Issue by RavikumarTulugu** [Yahweasel/libav.js#49]
latest emcc has removed the setting STACK_SIZE and renamed it to TOTAL_STACK ( my understanding ). to build wasm stuff successfully , the variable needs to be changed. I have tested and verified this with emcc-3.1.6 on ubuntu-23.10. 
Thanks

**Comment by Yahweasel** [comment]
You've got it backwards, I'm afraid. The latest emccs have removed `TOTAL_STACK` and renamed it to `STACK_SIZE`: https://github.com/emscripten-core/emscripten/blob/main/src/settings.js#L2140 . I do my builds with 3.1.40. You should use emsdk; the version in distros usually lags far behind.
