### ISSUE TITLE
parse mkv

### ISSUE THREAD

**Issue by iptvsmartws** [Yahweasel/libav.js#53]
Hello ,

any demo for parsing metadata from mkv video .
i want to get the subtitles .
any help ?

**Comment by Yahweasel** [comment]
I've never done subtitles in libav.js. It's possible/likely that you'd need a decoder that's not currently in any configuration, and/or some function that's not currently exposed. Regardless, the general answer is: libav.js is just a port of FFmpeg's libav libraries to C. The way you do it in libav.js is to learn how to do it in libav, and then do the same thing. I didn't make libav, so I don't know all the ins and outs, only the ones I use.
