### ISSUE TITLE
Feature request: support for writing to FileSystemFileHandle

### ISSUE THREAD

**Issue by marcello3d** [Yahweasel/libav.js#62]
There's [this API](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/createSyncAccessHandle) that's essentially designed for WebAssembly to have synchronous read/write access to a file.

Would it be reasonable to expose a way to make (and unmake) a writer device based on a FileSystemFileHandle and have that use createSyncAccessHandle under the hood? Could it potentially be more performant since it wouldn't need go through asyncify?

Currently we're using `mkwriterdev()` and the `libav.onwrite` callback to map this to libav.js, but that requires an extra worker layer.

**Comment by marcello3d** [comment]
We're doing it in a bunch of places, some is just muxing, some is audio encode + muxing. 

But as you suggest, from a pure performance perspective, it might not be the biggest savings. The main advantage is we currently need two layers of workers to write to the filesystem (because it's only supported in workers), and this would make everything much simpler.

**Comment by Yahweasel** [comment]
Added in 0d12712. `mkfsfhfile(name, fsfh)`, and `unlinkfsfhfile(name)` when you're done with it to close it.
