### ISSUE TITLE
Citation info for the project

### ISSUE THREAD

**Issue by reinhrst** [Yahweasel/libav.js#63]
Hi,

I'm about to publish a paper on my webapp that used libavjs (in an ecology journal), and I'd be happy to give credit where credit is due. Do you have a way to cite the project? Mostly in case you're active in the academic community IRL, you may want to make sure that I use the name under which you normally publish :).

If not, I can just see if they accept Yahweasel as a name, or else drop the citation altogether.

**Comment by reinhrst** [comment]
As an example of what could work:

https://github.com/ultralytics/ultralytics/blob/main/CITATION.cff

which becomes:

```
Jocher, G., Chaurasia, A., & Qiu, J. (2023). Ultralytics YOLO (Version 8.0.0) [Computer software]. https://github.com/ultralytics/ultralytics
```

or 

```
@software{Jocher_Ultralytics_YOLO_2023,
author = {Jocher, Glenn and Chaurasia, Ayush and Qiu, Jing},
license = {AGPL-3.0},
month = jan,
title = {{Ultralytics YOLO}},
url = {https://github.com/ultralytics/ultralytics},
version = {8.0.0},
year = {2023}
}
```

**Comment by Yahweasel** [comment]
I don't use my real name (my passport name) online for privacy reasons. I sometimes expand Yahweasel into the pseudonym "Yannis Wiesel", which you are free to use if you need something that seems a bit more like a name.

**Comment by reinhrst** [comment]
Thanks! Do I gather correctly from your response that you don't really care if you're mentioned in the paper. Because in that case just skipping the citation is probably the easier route (not sure how they would react to pseudonyms).

Obviously from the webapp page, a link will be forthcoming :)
