### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by Tsumiki** [Yahweasel/libav.js#71]
Trying to build a custom variant of webcodecs, but haven't actually gotten that far yet. 
Ran `Make build-webcodecs` and it failed to build, could be something environmental but I'm a little stuck at this point:
![image](https://github.com/user-attachments/assets/a053eeb2-4812-49c7-83d4-387c747d07fc)

**Comment by Yahweasel** [comment]
You probably have an ancient version of emscripten. The emscripten in most distros is uselessly old. Use [emsdk](https://emscripten.org/docs/tools_reference/emsdk.html).

**Comment by Tsumiki** [comment]
I was using emsdk, but for some reason it got itself upset, reactivated and reset the PATH, seemed to solve it, apologies for creating an issue, thanks for the steer! :)
