### ISSUE TITLE
Seeking to non-IDR keyframe

### ISSUE THREAD

**Issue by J3698** [Yahweasel/libav.js#72]
I noticed a few videos if I try to seek to non IDR keyframes, webcodecs breaks (since I flush the decoder upon seek). My current solution is to just locate these frames before hand, and I'm considering a solution where I just recover with some other logic. Wondering if there is a better way.

**Comment by Yahweasel** [comment]
There is not. This is a bug in WebCodecs, and the fact that they refuse to fix it does not make it not a bug. libav.js's seek (i.e., ffmpeg's seek) is based on the keyframe information in the container. It cannot decode frames to decide whether they're keyframes; it has to trust the container. The fact that *all* container formats mark non-IDR keyframes as keyframes and WebCodecs does not is a huge flaw in WebCodecs, but there's not a damned thing libav.js can do about it. It has no other source of this information.

The general solution and the solution I regularly use is to keep the very first frame in the file, and every time you seek, push through that frame after flushing. The very first frame will necessarily be the keyframiest keyframe. It's perfectly possible to create a file that doesn't start with a keyframe, breaking this, but it's always possible to get lost in a maze of what-ifs :)

**Comment by marcello3d** [comment]
Another thing to try for these files is to use software decoding mode in webcodecs
