### ISSUE TITLE
Add seek example/test with audio stream

### ISSUE THREAD

**Issue by lucadalli** [Yahweasel/libav.js#73]
I've been trying to seek an audio stream the same way I seek a video stream but it's not working as I intend. After decoding the sample, the timestamp of resultant AudioData does not match my requested `timestampUs`.
I'm not sure what I'm doing wrong, but it's likely the pts to ts conversion since that's the only other relevant code aside from the method call itself. Audio stream codec is Opus.

```
const ts =
  ((timestampUs / 1e6) * this.stream.time_base_den) /
  this.stream.time_base_num
await this.libav.avformat_seek_file_max(
  this.fmtCtx,
  this.stream.index,
  ts,
  0,
  0,
)
```

**Comment by Yahweasel** [comment]
Or if all of the packets you read were from a different stream. Regardless that seems to be an unrelated issue and I'm still not sure what issue you're reporting above.

Here's the situation with audio timestamps, not just in libav.js, but, as far as I can tell, in all audio decoders that exist: the audio timestamps in the file (and thus in the packets) are meaningless and ignored. At most, the timestamp of the very first one is used as an offset for all the other timestamps, to make it start at zero. The decoder always spits out a continuous stream of audio, and its timestamps are always predictable: previous timestamp plus previous size. If you want a seek to actually give discontinuous timestamps after decoding, you will need to dump and restart the decoder. I'm not sure if flushing a libav decoder or Chrome AudioDecoder will have the same effect or not.
